"""Built-in deprecation data. Sourced from provider docs; update periodically."""

from datetime import date

from llm_deprecation.models import DeprecationStatus, ModelInfo

# Canonical registry: provider -> model_id (normalized) -> ModelInfo
# Model IDs are stored lowercase for case-insensitive lookup.
# Sources: platform.openai.com/docs/models, platform.openai.com/docs/deprecations,
#          docs.anthropic.com (models + model-deprecations), ai.google.dev (Gemini models)
BUILTIN_REGISTRY: list[ModelInfo] = [
    # =============================================================================
    # OPENAI — https://platform.openai.com/docs/models, .../deprecations
    # =============================================================================
    # --- Active / current models ---
    ModelInfo(provider="openai", model_id="gpt-5.4", status=DeprecationStatus.ACTIVE, notes="Most capable model for professional work."),
    ModelInfo(provider="openai", model_id="gpt-5.4-pro", status=DeprecationStatus.ACTIVE, notes="Smarter, more precise version of GPT-5.4."),
    ModelInfo(provider="openai", model_id="gpt-5-mini", status=DeprecationStatus.ACTIVE, notes="Faster, cost-efficient GPT-5 for well-defined tasks."),
    ModelInfo(provider="openai", model_id="gpt-5-nano", status=DeprecationStatus.ACTIVE, notes="Fastest, most cost-efficient GPT-5."),
    ModelInfo(provider="openai", model_id="gpt-5", status=DeprecationStatus.ACTIVE, notes="Intelligent reasoning model for coding and agentic tasks."),
    ModelInfo(provider="openai", model_id="gpt-4.1", status=DeprecationStatus.ACTIVE, notes="Smartest non-reasoning model."),
    ModelInfo(provider="openai", model_id="gpt-4.1-mini", status=DeprecationStatus.ACTIVE, notes="Latency-sensitive tasks."),
    ModelInfo(provider="openai", model_id="gpt-4o", status=DeprecationStatus.ACTIVE, notes="Multimodal chat model."),
    ModelInfo(provider="openai", model_id="gpt-4o-mini", status=DeprecationStatus.ACTIVE, notes="Cost-efficient multimodal."),
    ModelInfo(provider="openai", model_id="gpt-3.5-turbo", status=DeprecationStatus.ACTIVE, notes="Legacy chat; prefer gpt-4.1-mini or gpt-5-mini."),
    ModelInfo(provider="openai", model_id="gpt-oss-120b", status=DeprecationStatus.ACTIVE, notes="Open-weight, Apache 2.0."),
    ModelInfo(provider="openai", model_id="gpt-oss-20b", status=DeprecationStatus.ACTIVE, notes="Open-weight, low latency."),
    ModelInfo(provider="openai", model_id="o3", status=DeprecationStatus.ACTIVE, notes="Reasoning model."),
    ModelInfo(provider="openai", model_id="o4-mini", status=DeprecationStatus.ACTIVE, notes="Faster reasoning."),
    ModelInfo(provider="openai", model_id="gpt-5.1-chat-latest", status=DeprecationStatus.ACTIVE, notes="ChatGPT-style chat."),
    ModelInfo(provider="openai", model_id="gpt-5-codex-mini", status=DeprecationStatus.ACTIVE, notes="Code generation with shell tool."),
    ModelInfo(provider="openai", model_id="gpt-image-1", status=DeprecationStatus.ACTIVE, notes="Image generation."),
    ModelInfo(provider="openai", model_id="gpt-image-1-mini", status=DeprecationStatus.ACTIVE, notes="Cost-efficient image generation."),
    ModelInfo(provider="openai", model_id="gpt-image-1.5", status=DeprecationStatus.ACTIVE, notes="State-of-the-art image generation."),
    ModelInfo(provider="openai", model_id="gpt-realtime", status=DeprecationStatus.ACTIVE, notes="Realtime text and audio."),
    ModelInfo(provider="openai", model_id="gpt-realtime-mini", status=DeprecationStatus.ACTIVE, notes="Cost-efficient realtime."),
    ModelInfo(provider="openai", model_id="gpt-audio", status=DeprecationStatus.ACTIVE, notes="Audio in/out with Chat Completions."),
    ModelInfo(provider="openai", model_id="gpt-audio-mini", status=DeprecationStatus.ACTIVE, notes="Cost-efficient audio."),
    ModelInfo(provider="openai", model_id="text-embedding-3-small", status=DeprecationStatus.ACTIVE, notes="Embeddings."),
    ModelInfo(provider="openai", model_id="text-embedding-3-large", status=DeprecationStatus.ACTIVE, notes="Embeddings."),
    ModelInfo(provider="openai", model_id="omni-moderation", status=DeprecationStatus.ACTIVE, notes="Moderation."),
    # --- Deprecated (with shutdown dates) ---
    ModelInfo(
        provider="openai",
        model_id="chatgpt-4o-latest",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 2, 17),
        replacement="gpt-5.1-chat-latest",
        notes="ChatGPT 4o snapshot; use gpt-5.1-chat-latest.",
    ),
    ModelInfo(
        provider="openai",
        model_id="codex-mini-latest",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 2, 12),
        replacement="gpt-5-codex-mini",
        notes="Legacy codex; use gpt-5-codex-mini.",
    ),
    ModelInfo(
        provider="openai",
        model_id="dall-e-2",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 5, 12),
        replacement="gpt-image-1 or gpt-image-1-mini",
        notes="Image generation; migrate to GPT Image 1.",
    ),
    ModelInfo(
        provider="openai",
        model_id="dall-e-3",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 5, 12),
        replacement="gpt-image-1 or gpt-image-1-mini",
        notes="Image generation; migrate to GPT Image 1.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-0314",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 26),
        replacement="gpt-5 or gpt-4.1",
        notes="Legacy GPT-4 snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-1106-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 26),
        replacement="gpt-5 or gpt-4.1",
        notes="Legacy GPT-4 preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-0125-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 26),
        replacement="gpt-5 or gpt-4.1",
        notes="Including gpt-4-turbo-preview aliases.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-turbo-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 26),
        replacement="gpt-5 or gpt-4.1",
        notes="Points to gpt-4-0125-preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-turbo-preview-completions",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 26),
        replacement="gpt-5 or gpt-4.1",
        notes="Points to gpt-4-0125-preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-3.5-turbo-instruct",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 9, 28),
        replacement="gpt-5-mini or gpt-4.1-mini",
        notes="Completions-style model.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-3.5-turbo-1106",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 9, 28),
        replacement="gpt-5-mini or gpt-4.1-mini",
        notes="Legacy GPT-3.5 snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="babbage-002",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 9, 28),
        replacement="gpt-5-mini or gpt-4.1-mini",
        notes="Base model.",
    ),
    ModelInfo(
        provider="openai",
        model_id="davinci-002",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 9, 28),
        replacement="gpt-5-mini or gpt-4.1-mini",
        notes="Base model.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-realtime-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-realtime",
        notes="Realtime beta; use gpt-realtime.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-realtime-preview-2025-06-03",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-realtime",
        notes="Realtime snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-realtime-preview-2024-12-17",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-realtime",
        notes="Realtime snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-mini-realtime-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-realtime-mini",
        notes="Realtime beta.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-audio-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-audio",
        notes="Audio preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-mini-audio-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 3, 24),
        replacement="gpt-audio-mini",
        notes="Audio preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-realtime-preview-2024-10-01",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 10),
        replacement="gpt-realtime",
        notes="Older realtime snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4o-audio-preview-2024-10-01",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 10),
        replacement="gpt-audio",
        notes="Older audio snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-moderation-007",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 27),
        replacement="omni-moderation",
        notes="Use omni-moderation.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-moderation-stable",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 27),
        replacement="omni-moderation",
        notes="Use omni-moderation.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-moderation-latest",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 27),
        replacement="omni-moderation",
        notes="Use omni-moderation.",
    ),
    ModelInfo(
        provider="openai",
        model_id="o1-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 7, 28),
        replacement="o3",
        notes="Reasoning; use o3.",
    ),
    ModelInfo(
        provider="openai",
        model_id="o1-mini",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 10, 27),
        replacement="o4-mini",
        notes="Reasoning; use o4-mini.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4.5-preview",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 7, 14),
        replacement="gpt-4.1",
        notes="Preview; use gpt-4.1.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-embedding-ada-002",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2025, 1, 1),
        replacement="text-embedding-3-small",
        notes="First-gen embeddings.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-3.5-turbo-0301",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 9, 13),
        replacement="gpt-3.5-turbo",
        notes="Original chat snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-3.5-turbo-0613",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 9, 13),
        replacement="gpt-3.5-turbo",
        notes="Chat snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-3.5-turbo-16k-0613",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 9, 13),
        replacement="gpt-3.5-turbo",
        notes="16k context snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-32k",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 6, 6),
        replacement="gpt-4o",
        notes="32k context.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-32k-0613",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 6, 6),
        replacement="gpt-4o",
        notes="32k snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-32k-0314",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 6, 6),
        replacement="gpt-4o",
        notes="32k snapshot.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-vision-preview",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 12, 6),
        replacement="gpt-4o",
        notes="Vision preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="gpt-4-1106-vision-preview",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 12, 6),
        replacement="gpt-4o",
        notes="Vision preview.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-ada-001",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 1, 4),
        replacement="gpt-3.5-turbo-instruct",
        notes="InstructGPT.",
    ),
    ModelInfo(
        provider="openai",
        model_id="text-davinci-003",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 1, 4),
        replacement="gpt-3.5-turbo-instruct",
        notes="InstructGPT.",
    ),
    ModelInfo(
        provider="openai",
        model_id="code-davinci-002",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2023, 3, 23),
        replacement="gpt-4o",
        notes="Codex.",
    ),
    # =============================================================================
    # ANTHROPIC — docs.anthropic.com (models + model-deprecations)
    # =============================================================================
    # --- Active ---
    ModelInfo(provider="anthropic", model_id="claude-opus-4-6", status=DeprecationStatus.ACTIVE, notes="Latest Opus; most capable."),
    ModelInfo(provider="anthropic", model_id="claude-sonnet-4-6", status=DeprecationStatus.ACTIVE, notes="Latest Sonnet; speed and intelligence."),
    ModelInfo(provider="anthropic", model_id="claude-haiku-4-5-20251001", status=DeprecationStatus.ACTIVE, notes="Latest Haiku; fastest."),
    ModelInfo(provider="anthropic", model_id="claude-haiku-4-5", status=DeprecationStatus.ACTIVE, notes="Alias for claude-haiku-4-5-20251001."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-5-20251101", status=DeprecationStatus.ACTIVE, notes="Opus 4.5 snapshot."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-5", status=DeprecationStatus.ACTIVE, notes="Opus 4.5 alias."),
    ModelInfo(provider="anthropic", model_id="claude-sonnet-4-5-20250929", status=DeprecationStatus.ACTIVE, notes="Sonnet 4.5 snapshot."),
    ModelInfo(provider="anthropic", model_id="claude-sonnet-4-5", status=DeprecationStatus.ACTIVE, notes="Sonnet 4.5 alias."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-1-20250805", status=DeprecationStatus.ACTIVE, notes="Opus 4.1 snapshot."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-1", status=DeprecationStatus.ACTIVE, notes="Opus 4.1 alias."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-20250514", status=DeprecationStatus.ACTIVE, notes="Opus 4 snapshot."),
    ModelInfo(provider="anthropic", model_id="claude-opus-4-0", status=DeprecationStatus.ACTIVE, notes="Opus 4 alias."),
    ModelInfo(provider="anthropic", model_id="claude-sonnet-4-20250514", status=DeprecationStatus.ACTIVE, notes="Sonnet 4 snapshot."),
    ModelInfo(provider="anthropic", model_id="claude-sonnet-4-0", status=DeprecationStatus.ACTIVE, notes="Sonnet 4 alias."),
    # --- Deprecated / Retired ---
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-haiku-20240307",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 4, 20),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude Haiku 3; migrate to Haiku 4.5.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-7-sonnet-20250219",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2026, 2, 19),
        replacement="claude-opus-4-6",
        notes="Claude Sonnet 3.7; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-5-haiku-20241022",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2026, 2, 19),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude Haiku 3.5; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-5-sonnet-20240620",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 10, 28),
        replacement="claude-opus-4-6",
        notes="Claude Sonnet 3.5; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-5-sonnet-20241022",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 10, 28),
        replacement="claude-opus-4-6",
        notes="Claude Sonnet 3.5; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-opus-20240229",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2026, 1, 5),
        replacement="claude-opus-4-6",
        notes="Claude Opus 3; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-3-sonnet-20240229",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 7, 21),
        replacement="claude-opus-4-6",
        notes="Claude Sonnet 3; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-2.1",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 7, 21),
        replacement="claude-opus-4-6",
        notes="Claude 2.1; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-2.0",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2025, 7, 21),
        replacement="claude-opus-4-6",
        notes="Claude 2.0; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-1.0",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude 1; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-1.1",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude 1.1; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-1.2",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude 1.2; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-1.3",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude 1.3; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-instant-1.0",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude Instant 1; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-instant-1.1",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude Instant 1.1; retired.",
    ),
    ModelInfo(
        provider="anthropic",
        model_id="claude-instant-1.2",
        status=DeprecationStatus.RETIRED,
        sunset_date=date(2024, 11, 6),
        replacement="claude-haiku-4-5-20251001",
        notes="Claude Instant 1.2; retired.",
    ),
    # =============================================================================
    # GOOGLE GEMINI — ai.google.dev/gemini-api/docs/models, Vertex AI docs
    # =============================================================================
    # --- Active ---
    ModelInfo(provider="gemini", model_id="gemini-2.5-pro", status=DeprecationStatus.ACTIVE, notes="Flagship reasoning and coding."),
    ModelInfo(provider="gemini", model_id="gemini-2.5-flash", status=DeprecationStatus.ACTIVE, notes="Balanced speed and accuracy."),
    ModelInfo(provider="gemini", model_id="gemini-2.5-flash-lite", status=DeprecationStatus.ACTIVE, notes="Budget, high-volume."),
    ModelInfo(provider="gemini", model_id="gemini-2.0-flash", status=DeprecationStatus.ACTIVE, notes="1M context, tool use, multimodal."),
    ModelInfo(provider="gemini", model_id="gemini-2.5-flash-live", status=DeprecationStatus.ACTIVE, notes="Realtime voice/video agents."),
    ModelInfo(provider="gemini", model_id="gemini-2.5-pro-tts", status=DeprecationStatus.ACTIVE, notes="Text-to-speech."),
    ModelInfo(provider="gemini", model_id="gemini-3.1-pro", status=DeprecationStatus.ACTIVE, notes="Preview; advanced reasoning and agentic."),
    ModelInfo(provider="gemini", model_id="gemini-3-flash", status=DeprecationStatus.ACTIVE, notes="Preview; frontier performance."),
    ModelInfo(provider="gemini", model_id="gemini-3.1-flash-lite", status=DeprecationStatus.ACTIVE, notes="Preview; frontier, reduced cost."),
    # --- Deprecated / legacy ---
    ModelInfo(
        provider="gemini",
        model_id="gemini-2.0-flash-001",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 6, 1),
        replacement="gemini-2.5-flash or gemini-2.0-flash",
        notes="Snapshot; migrate to 2.5 or current 2.0.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.5-pro",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 6, 17),
        replacement="gemini-2.5-pro or gemini-2.0-flash",
        notes="Not available in new Vertex projects from Apr 2025; migrate to 2.x.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.5-pro-002",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 6, 17),
        replacement="gemini-2.5-pro",
        notes="Updated 1.5 Pro; migrate to 2.5.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.5-flash",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 6, 17),
        replacement="gemini-2.5-flash or gemini-2.0-flash",
        notes="Not available in new Vertex projects from Apr 2025; migrate to 2.x.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.5-flash-002",
        status=DeprecationStatus.DEPRECATED,
        sunset_date=date(2026, 6, 17),
        replacement="gemini-2.5-flash",
        notes="Updated 1.5 Flash; migrate to 2.5.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.0-pro",
        status=DeprecationStatus.LEGACY,
        replacement="gemini-2.5-pro or gemini-2.0-flash",
        notes="Legacy; prefer 2.5 or 2.0.",
    ),
    ModelInfo(
        provider="gemini",
        model_id="gemini-1.0-flash",
        status=DeprecationStatus.LEGACY,
        replacement="gemini-2.5-flash",
        notes="Legacy; prefer 2.5 Flash.",
    ),
]


def get_builtin_registry() -> list[ModelInfo]:
    """Return a copy of the built-in registry (so callers can extend without mutating)."""
    return list(BUILTIN_REGISTRY)
